my_string = input('Hello ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print('Привет, я Настя, как твои дела?'.replace( " ", "#"))
print(my_string[0])
print(my_string[-1])